version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: pix-processor-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thushima
      POSTGRES_DB: pix_processor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pix-processor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  redis:
    image: redis:8.2.1-alpine
    container_name: pix-processor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pix-processor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

volumes:
  postgres_data:
  redis_data:

networks:
  pix-processor-network:
    driver: bridge
